apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: image-webapp
resources:
  - ../../base
images:
  - name: ghcr.io/justlee2512/image-webapp
    newName: ghcr.io/justlee2512/image-webapp
    newTag: sha-0952915b97936e31838ba805777850d7b87c1127
commonLabels:
  app.kubernetes.io/environment: production
