apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: image-webapp
resources:
  - ../../base
images:
  - name: ghcr.io/justlee2512/image-webapp
    newName: ghcr.io/justlee2512/image-webapp
    newTag: sha-8a7ed885c2286a1d804d4e346c45b2a88de43b65
commonLabels:
  app.kubernetes.io/environment: production
