apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: image-webapp
resources:
  - ../../base
images:
  - name: ghcr.io/justlee2512/image-webapp
    newName: ghcr.io/justlee2512/image-webapp
    newTag: sha-9d8ca2b2e8d3bd2ffb0e89f4b1219e069fb0ac2f
commonLabels:
  app.kubernetes.io/environment: production
