apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-webapp
  namespace: acgesd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/justlee2512/image-webapp-gitops.git
    targetRevision: main
    path: apps/image-webapp/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: image-webapp
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
